baseURL = 'https://deimoshall.dev/'
languageCode = 'en'
title = 'Deimos Hall'
defaultContentLanguage = "en"

theme = "hello-friend"
[pagination]
  pagerSize = 5

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  # defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # I moved it to the single pages
  # Show reading time in minutes for posts
  # showReadingTime = true

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true
  
  # Added by me
  defaultAuthor = 'Deimos Hall'

[languages]
  [languages.en]
    title = "Deimos Hall"
    languageName = "English"
    weight = 2

    [languages.en.params]
      keywords = ""
      subtitle = ""
      copyright = "By Deimos Hall | All rights reserved"
      menuMore = "Show more"
      writtenBy = "Written by"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      minuteReadingTime = "min read"
      dateFormatSingle = "2006-01-02"
      dateFormatList = "2006-01-02"
      # leave empty to disable, enter display text to enable
      # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "Deimos Hall"
      logoHomeLink = "/en"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/en"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "terms"
        name = "Terms and conditions"
        url = "/en"
        weight = 4



  [languages.es]
    title = "Deimos Hall"
    languageName = "Español"
    weight = 1
    [languages.es.params]
      keywords = ""
      subtitle = ""
      copyright = "Por Deimos Hall | Todos los derechos reservados"
      menuMore = "Mostrar mas"
      writtenBy = "Escrito por"
      readMore = "Leer más"
      readOtherPosts = "Leer otras publicaciones"
      newerPosts = "Nuevas publicaciones"
      olderPosts = "Publicaciones anteriores"
      minuteReadingTime = "minutos de lectura"
      dateFormatSingle = "2006-01-02"
      dateFormatList = "2006-01-02"
      # leave empty to disable, enter display text to enable
      # lastModDisplay = ""

    [languages.es.params.logo]
      logoText = "Deimos Hall"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "home"
        name = "Inicio"
        url = "/"
        weight = 1
      [[languages.es.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = 2
      [[languages.es.menu.main]]
        identifier = "about"
        name = "Acerca de mí"
        url = "/es/about"
        weight = 3
      [[languages.es.menu.main]]
        identifier = "terms"
        name = "Terminos y condiciones"
        url = "/"
        weight = 4